package com.github.zxj5470.bugktdoc.parser.psi

/**
 * @author zxj5470
 * @date 2018/4/2
 */
enum class BugKtDocStatus {
	CLASS,
	CLASS_OK,
	DECORATE_AT,
	DECORATING,
	FUN,
	FUN_GENERICS,
	FUN_LPAR,
	FUN_NAME,
	FUN_PARAM_NAME,
	FUN_PARAM_NAME_TYPE,
	FUN_PARAM_NAME_TYPE_COLON,
	FUN_PARAM_ASSIGN,
	FUN_RETURN_TYPE_COLON,
	FUN_RETURN_TYPE,
	FUN_OK,
	GENERICS_BEGIN,
	LEFT_BRACE,
	LEFT_BRACKET,
	LEFT_M_BRACKET,
	NOTHING,
	OK,
	STRING
}